-- +goose Up
CREATE TABLE IF NOT EXISTS "sysSsoClient" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" VARCHAR(128) NOT NULL,
    "clientName" VARCHAR(128) NOT NULL,
    "clientType" VARCHAR(32) NOT NULL,
    "clientAuthMethod" VARCHAR(32) NOT NULL DEFAULT 'none',
    "grantTypesJson" JSONB NOT NULL,
    "scopesJson" JSONB NOT NULL,
    "requirePkce" SMALLINT NOT NULL DEFAULT 1,
    "requireConsent" SMALLINT NOT NULL DEFAULT 0,
    "trustedFirstParty" SMALLINT NOT NULL DEFAULT 0,
    "accessTokenTtlSec" INT NOT NULL DEFAULT 1800,
    "refreshTokenTtlSec" INT NOT NULL DEFAULT 2592000,
    status SMALLINT NOT NULL DEFAULT 0,
    "metadataJson" JSONB NULL,
    "creatorId" BIGINT NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updaterId" BIGINT NULL,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoClient_clientId_deleted" UNIQUE ("clientId", "isDeleted")
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoClient_type_status_deleted" ON "sysSsoClient" ("clientType", status, "isDeleted");

CREATE TABLE IF NOT EXISTS "sysSsoClientRedirectUri" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" VARCHAR(128) NOT NULL,
    "redirectUri" VARCHAR(512) NOT NULL,
    "postLogoutRedirectUri" VARCHAR(512) NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "creatorId" BIGINT NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updaterId" BIGINT NULL,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoClientRedirectUri_client_uri_deleted" UNIQUE ("clientId", "redirectUri", "isDeleted")
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoClientRedirectUri_client_status_deleted" ON "sysSsoClientRedirectUri" ("clientId", status, "isDeleted");

CREATE TABLE IF NOT EXISTS "sysSsoClientSecret" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "clientId" VARCHAR(128) NOT NULL,
    "secretHash" VARCHAR(255) NOT NULL,
    "secretHint" VARCHAR(128) NULL,
    "expiresAt" TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "creatorId" BIGINT NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updaterId" BIGINT NULL,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoClientSecret_client_status_deleted" ON "sysSsoClientSecret" ("clientId", status, "isDeleted");

CREATE TABLE IF NOT EXISTS "sysSsoAuthorizationCode" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    "clientId" VARCHAR(128) NOT NULL,
    "userId" BIGINT NOT NULL,
    "sessionId" VARCHAR(128) NOT NULL,
    "redirectUri" VARCHAR(512) NOT NULL,
    "scopesJson" JSONB NOT NULL,
    "codeChallenge" VARCHAR(255) NULL,
    "codeChallengeMethod" VARCHAR(32) NULL,
    nonce VARCHAR(255) NULL,
    acr VARCHAR(64) NULL,
    "amrJson" JSONB NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "consumedAt" TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "metadataJson" JSONB NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoAuthorizationCode_code_deleted" UNIQUE (code, "isDeleted")
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoAuthorizationCode_client_user_status" ON "sysSsoAuthorizationCode" ("clientId", "userId", status);

CREATE TABLE IF NOT EXISTS "sysSsoConsentGrant" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT NOT NULL,
    "clientId" VARCHAR(128) NOT NULL,
    "scopesJson" JSONB NOT NULL,
    "grantedAt" TIMESTAMPTZ NOT NULL,
    "revokedAt" TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "metadataJson" JSONB NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoConsentGrant_user_client_deleted" UNIQUE ("userId", "clientId", "isDeleted")
);

CREATE TABLE IF NOT EXISTS "sysSsoSession" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "sessionId" VARCHAR(128) NOT NULL,
    "userId" BIGINT NOT NULL,
    "clientId" VARCHAR(128) NOT NULL,
    "deviceId" VARCHAR(128) NULL,
    "loginIp" VARCHAR(64) NULL,
    "userAgent" VARCHAR(1024) NULL,
    acr VARCHAR(64) NULL,
    "amrJson" JSONB NULL,
    "loginAt" TIMESTAMPTZ NOT NULL,
    "lastAccessAt" TIMESTAMPTZ NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "revokedAt" TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "metadataJson" JSONB NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoSession_sessionId_deleted" UNIQUE ("sessionId", "isDeleted")
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoSession_user_status_deleted" ON "sysSsoSession" ("userId", status, "isDeleted");

CREATE TABLE IF NOT EXISTS "sysSsoRefreshTokenFamily" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "familyId" VARCHAR(128) NOT NULL,
    "sessionId" VARCHAR(128) NOT NULL,
    "clientId" VARCHAR(128) NOT NULL,
    "userId" BIGINT NOT NULL,
    "currentTokenHash" VARCHAR(255) NOT NULL,
    "previousTokenHash" VARCHAR(255) NULL,
    "reuseDetected" SMALLINT NOT NULL DEFAULT 0,
    "rotatedAt" TIMESTAMPTZ NULL,
    "expiresAt" TIMESTAMPTZ NOT NULL,
    "revokedAt" TIMESTAMPTZ NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    "metadataJson" JSONB NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoRefreshTokenFamily_family_deleted" UNIQUE ("familyId", "isDeleted")
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoRefreshTokenFamily_currentTokenHash_deleted" ON "sysSsoRefreshTokenFamily" ("currentTokenHash", "isDeleted");

CREATE TABLE IF NOT EXISTS "sysSsoIssuerKey" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kid VARCHAR(128) NOT NULL,
    algorithm VARCHAR(32) NOT NULL,
    "publicKeyPem" TEXT NOT NULL,
    "privateKeyCiphertext" TEXT NULL,
    "keyStatus" VARCHAR(32) NOT NULL,
    "activateAt" TIMESTAMPTZ NULL,
    "retireAt" TIMESTAMPTZ NULL,
    "metadataJson" JSONB NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "uk_sysSsoIssuerKey_kid_deleted" UNIQUE (kid, "isDeleted")
);

CREATE TABLE IF NOT EXISTS "sysSsoAuditLog" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "eventType" VARCHAR(64) NOT NULL,
    "clientId" VARCHAR(128) NULL,
    "userId" BIGINT NULL,
    "sessionId" VARCHAR(128) NULL,
    "deviceId" VARCHAR(128) NULL,
    "tenantId" VARCHAR(128) NULL,
    "loginIp" VARCHAR(64) NULL,
    "userAgent" VARCHAR(1024) NULL,
    result VARCHAR(32) NOT NULL,
    "reasonCode" VARCHAR(64) NULL,
    "detailJson" JSONB NULL,
    "traceId" VARCHAR(128) NULL,
    "createTime" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isDeleted" SMALLINT NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "idx_sysSsoAuditLog_trace_deleted" ON "sysSsoAuditLog" ("traceId", "isDeleted");

-- +goose Down
DROP TABLE IF EXISTS "sysSsoAuditLog";
DROP TABLE IF EXISTS "sysSsoIssuerKey";
DROP TABLE IF EXISTS "sysSsoRefreshTokenFamily";
DROP TABLE IF EXISTS "sysSsoSession";
DROP TABLE IF EXISTS "sysSsoConsentGrant";
DROP TABLE IF EXISTS "sysSsoAuthorizationCode";
DROP TABLE IF EXISTS "sysSsoClientSecret";
DROP TABLE IF EXISTS "sysSsoClientRedirectUri";
DROP TABLE IF EXISTS "sysSsoClient";
