-- +goose Up
-- Goal-3 adds a per-user mailbox sequence without deleting recipient history.

CREATE TABLE IF NOT EXISTS "public"."sysNotificationMailbox" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "scopeId" character varying(128) NOT NULL,
    "userId" BIGINT NOT NULL,
    "mailboxKey" character varying(96) NOT NULL,
    "changeSequence" BIGINT NOT NULL DEFAULT 0,
    "createTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updateTime" timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "ukNotificationMailboxOwner"
    ON "public"."sysNotificationMailbox" ("scopeId", "userId");
CREATE UNIQUE INDEX IF NOT EXISTS "ukNotificationMailboxKey"
    ON "public"."sysNotificationMailbox" ("mailboxKey");

WITH ranked AS (
    SELECT "id",
           ROW_NUMBER() OVER (PARTITION BY "scopeId", "userId" ORDER BY "createTime" ASC, "id" ASC) AS "sequenceValue"
    FROM "public"."sysNotificationRecipient"
)
UPDATE "public"."sysNotificationRecipient" AS recipient
SET "mailboxVersion" = ranked."sequenceValue"
FROM ranked
WHERE recipient."id" = ranked."id";

INSERT INTO "public"."sysNotificationMailbox" ("scopeId", "userId", "mailboxKey", "changeSequence")
SELECT seeded."scopeId",
       seeded."userId",
       'mbx_' || md5(seeded."scopeId" || ':' || seeded."userId"::text),
       seeded."changeSequence"
FROM (
    SELECT "scopeId", "userId", MAX("mailboxVersion") AS "changeSequence"
    FROM "public"."sysNotificationRecipient"
    GROUP BY "scopeId", "userId"
) AS seeded
ON CONFLICT ("scopeId", "userId") DO UPDATE
SET "changeSequence" = GREATEST("sysNotificationMailbox"."changeSequence", EXCLUDED."changeSequence"),
    "updateTime" = CURRENT_TIMESTAMP;

-- +goose Down
-- Forward-only: use a manual, audited retention plan instead of dropping
-- recipient or mailbox synchronization history.
-- +goose StatementBegin
DO $$
BEGIN
  RAISE EXCEPTION 'forward-only notification mailbox sync migration cannot be rolled back automatically';
END
$$;
-- +goose StatementEnd
