-- +goose Up
ALTER TABLE sysSsoSession
  MODIFY COLUMN createTime DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间';

ALTER TABLE sysSsoRefreshTokenFamily
  MODIFY COLUMN createTime DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '创建时间';

-- +goose Down
ALTER TABLE sysSsoSession
  MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE sysSsoRefreshTokenFamily
  MODIFY COLUMN createTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
